services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
    depends_on: []
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"